spring:
  datasource:
    url: jdbc:h2:mem:aetherdemo;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.SQL: INFO